# deployment of 2-tier app using single ansible script
---
- name: installation of appserver
  hosts: App_server
  become: yes
  vars: 
    packages:
      - nginx
      - php
      - php-fpm
    services: 
      - nginx
      - php-fpm
    web_file_path: /usr/share/nginx/html/index.php
  tasks:
  # install nginx, php
  - name: install nginx,php,php-fpm
    ansible.builtin.dnf:
      name: "{{packages}}"
      state: present
  - name: start and enable nginx,php-fpm
    ansible.builtin.systemd_service:
      name: "{{item}}"
      state: started
      enabled: true
    loop: "{{services}}"

  # deployment of php page
  - name: deploy php
    ansible.builtin.copy:
      dest: "{{web_file_path}}"
      content: |
       <?php
        phpinfo();
        ?>

# DB server
- name: installation of DB server
  hosts: DB_server
  become: yes
  vars:
   db_pkg: mariadb105-server
   db_service: mariadb
   db_name: FCT
  tasks:
  # install mariadb
  - name: install mariadb
    ansible.builtin.dnf:
      name: "{{db_pkg}}"
      state: present

  # start mariadb
  - name: start and enable mariadb
    ansible.builtin.systemd_service:
       name: "{{db_service}}"
       state: started
       enabled: true

  # create database
  - name: create a mysql database
    ansible.builtin.shell: |
     mysql -u root -e "CREATE DATABASE IF NOT EXISTS {{db_name}};"
