---
- name: install , start, enable nginx
  hosts: localhost
  become: yes # it assign sudo  privilages
  tasks:
  # install nginx
  - name: install nginx
    ansible.builtin.dnf:
     name: nginx
     state: present

     # start and enabled httpd
  - name: start and enabled nginx
    ansible.builtin.systemd_service:
     name: nginx
     state: started
     enabled: true

     # deploy index.html
  - name: deploy index.html file
    ansible.builtin.copy:
     dest: /usr/share/nginx/html/index.html
     content: |
       <h1>welcome to my nginx website</h1>
