# install nginx with handler block
---
- name: deployment of nginx with handler
  hosts: target_server
  become: yes
  vars:
    pkg: nginx
    svc: nginx
    file_path: /usr/share/nginx/html/index.html
    conf_file: /etc/nginx/conf.d/custom.conf
  tasks:
  #install nginx
   - name: install nginx 
     ansible.builtin.dnf: 
       name: "{{pkg}}"
       state: present

   - name: start and enable nginx
     ansible.builtin.systemd_service:
       name: "{{svc}}"
       state: started
       enabled: true

     #add configuration block
   - name: add configuration block
     ansible.builtin.blockinfile:
       path: "{{conf_file}}"
       create: yes
       block: |
         http {

              server {

                  listen 80;
 

                  location / {

                      root /usr/share/nginx/html;

                      index index.html index.htm;

                  }
              }
          }
     notify: restart nginx
  # deploy index.html
   - name: deployment of index page
     ansible.builtin.copy:
       dest: "{{file_path}}"
       content: <h1> This app is with handler from {{inventory_hostname}}</h1>

   # handler
  handlers:
  - name: restart nginx
    ansible.builtin.systemd_service:
       name: "{{svc}}"
       state: restarted
      

